### ISSUE TITLE
[EPIC] Station Logic (game loop) + PDF Logic For Station

### ISSUE THREAD

**Issue by MCCello** [Best-Tim/IndustryProject#14]
- [x] Station 1: Dissolving Cotton in Zinc Chloride & spaghettify it. @guitartrick33 @vladchi2 
- [x] Station 2: Dryer Wheel @MCCello @simulateduniverse 
- [ ] Station 3: Carbonize Cable
- [ ] Station 4: Sticking Filament to Contact Wires
- [ ] Station 5: Seal & Vacuum the lightbulb
