### ISSUE TITLE
Instructions Table Canvas Manager (Main Logic)

### ISSUE THREAD

**Issue by MCCello** [Best-Tim/IndustryProject#17]
- [ ] The code shuold be extensible and reusable enough to be able to implement any number of new Canvases' in order to support station minigame puzzles.
       - [ ] The main Book UI will be here
       - [ ] Temperature Gauge -> for Station 3 #14 
       - [ ] Pressure Gauge -> for Station 1 #14 
       - [ ] Tension Gauge -> for Station 2 #14 
       - [ ] Timer -> for Station 5 #14 
- [ ] Quiz Generator for main Book UI randomizer
